### ISSUE TITLE
TurtleSim

### ISSUE THREAD

**Issue by agerami20** [ros/ros_tutorials#92]
I cannot get turtlesim to work for the life of me. I have tried all the ros answers discussion but nothing works and it just messes with my system files. When I try to run the command: rosrun turtlesim turtlesim_node I get the error:
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)

Please help!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

---

> I have tried all the ros answers discussion but nothing works and it just messes with my system files.

Which ones have you tried? Please reference them to avoid going through the same thing again.

Also include information like what platform are you on, what ROS version are you using, what version of Qt do you use, etc.
