### ISSUE TITLE
turtlesim: Support commanding the turtles with holonomic motion

### ISSUE THREAD

**Issue by Tiryoh** [ros/ros_tutorials#93]
I made a change to turtlesim and support commanding the turtles with holonomic motion, like an omni-directional robot.

https://github.com/Tiryoh/omni_turtlesim_ros2

![Image from Gyazo](https://i.gyazo.com/974e67e38431b10c9985c9b033eed577.gif)

At first I was going to release it as a separate package, but I was advised to integrate it into this package (https://github.com/ros/rosdistro/pull/25854).

Is it possible to integrate this feature into turtlesim? I'd like to open the PR to the following branches if this feature would be welcome.

* melodic-devel
* noetic-devel
* dashing-devel
* eloquent-devel
* foxy-devel

**Comment by dirk-thomas** [comment]
`turtlesim` is meant as an example demonstrating the concepts of ROS. It tries to be simple and easy to understand. 

I don't see how strafing and changing the speed adds any value for beginners of ROS - on the opposite I think these additions would make the code more complex and difficult to understand.

What benefit would this feature bring to users when learning ROS?

@jacobperron FYI

**Comment by jacobperron** [comment]
IIUC, allowing for holonomic motion in the simulator doesn't change the users experience going through the tutorials (assuming the turtlesim teleop node doesn't change; I don't think it should), but if someone wanted to command it in this way with another node they could.

I think there's value in allowing someone to experiment with their own controllers in a less constrained way. But it would be good to hear if there's a more specific use-case.

I don't think the change adds much complexity; I think this is the diff: https://github.com/Tiryoh/omni_turtlesim_ros2/commit/989cf0f0471cae7bda1128c55695540543144149

**Comment by Tiryoh** [comment]
@dirk-thomas, thank you for your responding.
@jacobperron, thank you for your comment.

> IIUC, allowing for holonomic motion in the simulator doesn't change the users experience going through the tutorials (assuming the turtlesim teleop node doesn't change; I don't think it should), but if someone wanted to command it in this way with another node they could.

> I don't think the change adds much complexity; I think this is the diff: Tiryoh/omni_turtlesim_ros2@989cf0f

Yes, I don't plan to change the users experience who are learning ROS through the tutorials through this update, and I have no plan to update the turtlesim teleop node.
I think it would be nice if the turtlesim node can receive linear.y twist messages in addition to the current function. The controller node in the figure (https://github.com/ros/ros_tutorials/issues/93#issue-663785308) is the [teleop_twist_keyboard](http://wiki.ros.org/teleop_twist_keyboard). I don't plan to merge this controller node to the turtlesim package.

> `turtlesim` is meant as an example demonstrating the concepts of ROS.

I think I understand what this means.  I understood that you are arguing that the ROS tutorials with turtlesim should be easy to learn for beginners, is my understanding consistent with your opinion?

> I don't see how strafing and changing the speed adds any value for beginners of ROS - on the opposite I think these additions would make the code more complex and difficult to understand.
>
> What benefit would this feature bring to users when learning ROS?

There is a demand to use ROS with omni-directional robots.
If turtlesim could handle linear.y twisted messages in addition to angular.z and linear.x, I think it would be an easy way to introduce the ROS beginners that twist message can send a command to the omni-directional robots.

**Comment by dirk-thomas** [comment]
> I don't think the change adds much complexity; I think this is the diff: Tiryoh/omni_turtlesim_ros2@989cf0f

The screenshot indicated additional changes to the `teleop` node so I assumed those would also be part of the patch.

> I don't plan to merge this controller node to the turtlesim package.

:+1:

@Tiryoh Please go ahead and create a pull request targeting the default branch and we can iterate on the patch if necessary.

**Comment by Tiryoh** [comment]
@dirk-thomas I made a Pull Request #94.  Could you check it out?

**Comment by dirk-thomas** [comment]
Addressed by #94.

**Comment by tianb03** [comment]
I just find out that the turtle is holonomic now.  Because I am teaching ROS these years so want to share some thoughts here though this issue is closed.

Introducing the holonomic movement into Turtlesim is great, it does not change the learning experience. And I also want this feature to test some easy multi-robot formation or cooperation stuff. **However, it brings in some confusion during learning TF using turtle_tf.** My students now solve the problem mainly based on the global info, the relation between two turtles can be ignored and you can command the follower based on v.x and v.y with a zero-valued a.z. A differential model may indicate that the follower must perceive the target turtle.

Moreover, the kinematic model of the turtle is no longer the same as a Turtlebot. 

It won't be a problem during our class. I don't know how this will affect the self-learner. I think your intuition is considerable @dirk-thomas .  I prefer a default differential turtle and can be switched to omni-directional. 

best regards,

**Comment by jacobperron** [comment]
@tianb03 Please avoid commenting on old and closed tickets since the comments will not be that visible. Prefer to open a new ticket (if there is not already one open). 

Having an option to disable holonomic motion sounds okay to me. I would lean towards leaving the holonomic feature on by default though, so as to not break existing "out-of-box" behavior. Please consider proposing the change as a new ticket (preferably in the form as a pull request)!
